graph:
  type: "tree_with_grid" 
  # star,tree, cycle, path, complete, erdos_reyni, lattice
  # sbm, geometric, tree_of_cycles, tree_with_grid
  # molecule_like, hierarchical
  n : 100
  p : 0.1 # Erdos-Reyni
  sizes : [25,25] # SBM
  p_intra : [0.3,0.3,0.3] # SBM 
  p_inter : 0.002  # SBM
  geometric_radius : 0.2 # random geometric
  tree_height : 3 # tree with grid, tree of cycles, hierarchical
  leaves_per_node : 2 # tree with grid, tree of cycles, hierarchical
  cycle_size : 8 # tree of cycles
  n_cycles : 4 # tree of cycles
  size_grid : 4 # tree with grid
  random_edges_added : 0 # hierarchical 
optimization:
  temperature: 0.5
  geometric_temperature : 1
  lambda_reg: 0.5
  alpha_diffusion: 2
  sigma : 10
  time : 5
  target_nodes : [0]
  k : 50
